name: howdy
description: Howdy app made by TNTeam.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^4.1.2+1
  firebase_core:
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  provider: ^4.3.2+3
  google_sign_in: ^4.0.1+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true